FROM python:3.7-alpine

COPY ./requirements.txt /
WORKDIR /

RUN apk add musl-dev linux-headers g++ gcc gfortran python-dev py-pip build-base wget freetype-dev libpng-dev openblas-dev
RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN pip install numpy
RUN pip install scipy
